### ISSUE TITLE
redis配置问题

### ISSUE THREAD

**Issue by mqgao** [kekingcn/spring-boot-klock-starter#10]
默认读取系统的redis然后注入，不需要那么复杂，或者找不到时默认注入session对象也行

**Comment by shang7053** [comment]
redisson唯一麻烦的是需要初始化就确定redis的集群模式，在开发测试线上环境不一致时，需要写代码做适配，kl既然对redisson做了封装，那为何不考虑把这个也优化掉，自动识别redis模式，然后初始化对应的信息？

**Comment by klboke** [comment]
自动识别不是很清楚，目前可以通过配置来区分的

**Comment by Nicqiang** [comment]
既然都是springboot-start,提出几个问题
1、采用spring-boot-redis的配置模式，而不是自己定义，支持用户传入redisTemplate
2、可扩展支持zk。自动识别，或者让用户重传入。

**Comment by klboke** [comment]
问题一：这里的实现使用了redisson中的封装，配置时也主要区别业务的redis配置
问题二：zk的话可以考虑分支start
