### ISSUE TITLE
maven 的依赖

### ISSUE THREAD

**Issue by muggle0** [kekingcn/spring-boot-klock-starter#14]
只有
<dependency>
     <groupId>cn.keking</groupId>
      <artifactId>spring-boot-klock-starter</artifactId>
       <version>1.1-RELEASE</version>
  </dependency>

还请补全快速开始之类的文档，感谢分享

**Comment by klboke** [comment]
可以先自己构建依赖，中央仓库上传会比较慢

**Comment by klboke** [comment]
已更新依赖
