### ISSUE TITLE
自定义处理方法

### ISSUE THREAD

**Issue by FaithStart** [kekingcn/spring-boot-klock-starter#17]
![image](https://user-images.githubusercontent.com/32026230/61509262-4a13d580-aa20-11e9-9dab-ef66d7434736.png)
![image](https://user-images.githubusercontent.com/32026230/61509409-db834780-aa20-11e9-896f-50f1dd5f3517.png)
自定义超时以及释放锁的处理方法，入参是方法名，但是会报错没有这个方法，这里入参是全限定路径还是什么？

**Comment by klboke** [comment]
方法不要加括号（）

**Comment by FaithStart** [comment]
我都试了哦，一样报错，直接 test
![image](https://user-images.githubusercontent.com/32026230/61510824-2011e180-aa27-11e9-896e-81739ddb192b.png)

**Comment by klboke** [comment]
降级的方法的入参和业务方法的入参要保持一致

**Comment by FaithStart** [comment]
![image](https://user-images.githubusercontent.com/32026230/61511076-1b016200-aa28-11e9-9801-7f838babff83.png)
降级的方法是什么意思，是说自定义的方法入参要和这些保持一致么

**Comment by klboke** [comment]
你帖代码块吧，我帮你改下

**Comment by FaithStart** [comment]
@Klock(waitTime = 10,keys = {"#userId"},releaseTimeoutStrategy = ReleaseTimeoutStrategy.FAIL_FAST,customLockTimeoutStrategy = "test")
    public String getValue(String userId,@KlockKey int id)throws Exception{
        Thread.sleep(40*1000);
        return "success";
    }
    //自定义失败处理
    public void test(LockInfo lockInfo, Lock lock, JoinPoint joinPoint){
        System.out.println("自定义失败错误");
    }

**Comment by klboke** [comment]
@klock(waitTime = 10,keys = {"#userId"},releaseTimeoutStrategy = ReleaseTimeoutStrategy.FAIL_FAST,customLockTimeoutStrategy = "test")
public String getValue(String userId,@KlockKey int id)throws Exception{
Thread.sleep(40*1000);
return "success";
}
//自定义失败处理
public String test(String userId, int id){
System.out.println("获取锁失败后的降级处理策略");
}

**Comment by FaithStart** [comment]
好的，感谢，方便问一句这是为什么吗

**Comment by klboke** [comment]
和熔断器降级的原理是一样，这样就可以在降级的方法里获取到原来方法的入参做一些事情

**Comment by FaithStart** [comment]
噢，明白了，感谢指教
