### ISSUE TITLE
不支持redis  Sentinel集群么？

### ISSUE THREAD

**Issue by liangxp** [kekingcn/spring-boot-klock-starter#2]
不支持redis  Sentinel集群么？

**Comment by klboke** [comment]
支持的

**Comment by dcmr** [comment]
怎么配置哨兵机制的？

**Comment by klboke** [comment]
请参考官方的配置文档：https://github.com/redisson/redisson/wiki/2.-%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95#27-%E5%93%A8%E5%85%B5%E6%A8%A1%E5%BC%8F ，klock会检查是否有redisson实例，如果配置过就不会装载
