### ISSUE TITLE
希望能使用spring.redis.xxx的配置

### ISSUE THREAD

**Issue by 5kywa1ker** [kekingcn/spring-boot-klock-starter#21]
spring:  
  klock:
    address: ${spring.redis.host}+${spring.redis.port}
    password: ${spring.redis.password}
    database: ${spring.redis.database}

**Comment by klboke** [comment]
使用spring.klock前缀是为了和业务redis的配置区分开，如果想要自己配置，可以使用业务redis配置覆盖klock的，klock的配置默认优先级是比较低的
