### ISSUE TITLE
关于keys，有几个问题想请教下

### ISSUE THREAD

**Issue by xingye311** [kekingcn/spring-boot-klock-starter#25]
keys里面目前支持添加常量么？还有从实体类里取值做key的时候，当某个取值是null的时候，会报空指针，这个能否优化下？多谢

**Comment by klboke** [comment]
你好，感谢提供这个宝贵的空指针的案例，我们已经在https://github.com/kekingcn/spring-boot-klock-starter/commit/86e347c248e6509c3c50b2f1e10d270fe30e0654 这个提交里修复了，
另keys支持添加常量是下面代码所示的意思么：
`
    public static final String LOCKKEY ="#userId";
    
    @Klock(keys = {LOCKKEY})
    public String getValue(String userId,@KlockKey Integer id)throws Exception{
        Thread.sleep(60*1000);
        return "success";
    }
`

**Comment by lcyan** [comment]
>     @Klock(keys = {LOCKKEY})

类似于@Klock(keys = {"100000"})这种的吧

**Comment by klboke** [comment]
可以的，但是不是通过keys设置，keys是获取业务入参的，通过name设置锁的名字，默认@Klock不加任何参数，name就是类名+方法名
