### ISSUE TITLE
同一线程中嵌套调用引发的问题

### ISSUE THREAD

**Issue by ipodtree** [kekingcn/spring-boot-klock-starter#26]
在同一线程中，如果由一个带klock锁（锁A）的方法调用另一个带klock锁（锁B）的方法，currentThreadLock中的锁信息将会更新（锁A->锁B），
` currentThreadLock.set(lock);
   currentThreadLockRes.get().setRes(true);
`

并且在两个方法退出时，都会触发KlockAspectHandler类中releaseLock方法的调用，
`      LockRes lockRes = currentThreadLockRes.get();
        if (lockRes.getRes()) {
            boolean releaseRes = currentThreadLock.get().release();
            // avoid release lock twice when exception happens below
            lockRes.setRes(false);
            if (!releaseRes) {
                handleReleaseTimeout(klock, lockRes.getLockInfo(), joinPoint);
            }
        }
`
由于第一次触发时，currentThreadLock和currentThreadLockRes中的锁信息会被清空，所以第二次触发将会报NPE。请教下，这种单一线程只支持加一次锁的设计，是有什么原因吗？另在有currentThreadLock这个ThreadLocal保证单一线程只有一个锁有效的前提下，currentThreadLockRes存在的意义是什么？

**Comment by klboke** [comment]
非常感谢你的反馈，下面就你的问题作出如下解答，未尽之处可以继续追问
## 空指针问题
你看的可能是老的代码，最新的代码已经修复了在同一个请求里加多个锁导致的NPE的问题。当时设计的时候确实没有考虑到同一个请求里加多把锁的情况，并不是有意这么设计的，但是目前我们这边的实际使用情况确实和你遇到的场景一样，还是比较复杂的，所以在修复NPE的问题的同时也就兼顾到了多线程多把锁单线程多把锁等情况。具体可以看看最新的代码。如果线上有使用，尽量更新到最新的版本
## 关于currentThreadLock的作用
currentThreadLockRes存在的意义是为了兼容spring里服务方法加了事务注解而加上的，在包含了事务的锁里，只有在事务结束后释放锁才有意义。具体参见：https://github.com/kekingcn/spring-boot-klock-starter/commit/0133095645c0218ac15d581f966aefe431d8c860

**Comment by klboke** [comment]
没问题，就先关闭这个issue了，还有问题可以继续打开
