### ISSUE TITLE
难道整个系统只有4把锁????

### ISSUE THREAD

**Issue by 91wangmeng** [kekingcn/spring-boot-klock-starter#3]
@PostConstruct
    public void init(){
        lockMap.put(LockType.Reentrant,new ReentrantLock(redissonClient));
        lockMap.put(LockType.Fair,new FairLock(redissonClient));
        lockMap.put(LockType.Read,new ReadLock(redissonClient));
        lockMap.put(LockType.Write,new WriteLock(redissonClient));
        logger.info("Klock Initialization Successful");
    }

    public Lock getLock(ProceedingJoinPoint joinPoint, Klock klock){
        LockInfo lockInfo = lockInfoProvider.get(joinPoint,klock);
        return lockMap.get(lockInfo.getType()).setLockInfo(lockInfo);
    }

根据LockFactory这个类,每种类型永远只有一把锁???  也就是同一个系统类,如果两个接口没什么关系,但是如果都用了公平锁,就意味着两个接口存在锁竞争?

**Comment by klboke** [comment]
这里是四种类型的锁，具体的锁，在reids中

**Comment by 91wangmeng** [comment]
@klboke 但是根据源码  这里面一种类型获取的都是同一把锁,却别就是lockInfo不同而已,, 这就导致,如果我一个操作嵌套了另外一个加锁的方法,内存方法的锁就会覆盖外层方法的锁,,导致内层的锁释放两次,而外层的锁无法自动释放,需要等待到lesstime才能释放

**Comment by klboke** [comment]
不清楚你的意思，方法执行前拿到锁，执行后释放锁

**Comment by qrqhuang** [comment]
Lock的实现中访问了成员变量`rLock`， 是线程不安全的。
同意LZ观点。

**Comment by klboke** [comment]
能否提供个具体线程不安全的例子，redisson的锁本身是加了线程id的

**Comment by 91wangmeng** [comment]
@klboke 比如
class A{
   //注入
   B b;

 //公平锁
   a(){
   b.b();
  };
}
class B{
  //公平锁
  b(){
  }
}
那根据那在执行方法a()里面的方法b的时候,由于是同一个线程,那b也方法可以获取到公平锁,然后将自己的锁信息通过 lockMap.get(lockInfo.getType()).setLockInfo(lockInfo)放入公平锁对象内,这时候外层a方法的公平锁信息就丢失了,会导致b方法执行完释放锁以后,a方法进行锁释放时,此时的锁信息是b方法的锁信息,所以释放的还是b方法的锁,而a方法的锁却无法得到释放,

**Comment by klboke** [comment]
@91wangmeng 感谢你的反馈，问题已确认并修复
