### ISSUE TITLE
关于 Aop 事务问题

### ISSUE THREAD

**Issue by chenlingmin** [kekingcn/spring-boot-klock-starter#5]
这个项目不错👍

给几点使用的建议：

1. Spring 中 Aop 有两种实现方式，是不是得考虑扩展？
2. 另外目前的切面中 默认是 aop 事务先行，而后再进入切面，很多有事物的方法就不适合了
3. 是否可以考虑多种锁的实现方式， 像 [shedlock](https://github.com/lukas-krecan/ShedLock) 这样

**Comment by klboke** [comment]
https://github.com/kekingcn/spring-boot-klock-starter/pull/9
