### ISSUE TITLE
klock不生效

### ISSUE THREAD

**Issue by whucsfzf** [kekingcn/spring-boot-klock-starter#7]
您好，在springboot项目中，运用了klock，用法如下：
@Klock
@Scheduled(fixedRate = 500)
public get(){
}
klock配置如下：
waitTime: 600
leaseTime: 600
但发现偶尔还是会导致get方法执行两次，请问下我的用法是否有问题？

**Comment by klboke** [comment]
不清楚你的使用场景，不好判断

**Comment by shang7053** [comment]
你这定时器，我猜你的需求是同一时间只运行一个，你get执行两次是因为起了两个实例，然后kl运行下他们顺序执行的

**Comment by tangshd** [comment]
看一下注解的顺序，是否真正锁住了

**Comment by whucsfzf** [comment]
发现问题了，锁使用的问题，正确用法：
A  a;
@scheduled(fixedRate = 500)
public get(){
     a.test();
}

class  A {
    @klock
    public  test(){
    }
}
